# Generated by Django 3.1.7 on 2021-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=50, unique=True)),
                ('Slug', models.CharField(max_length=50, unique=True)),
                ('Descreption', models.CharField(blank=True, max_length=100)),
                ('Cat_Image', models.ImageField(blank=True, upload_to='photo/categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
